# Generated by Django 5.1.15 on 2026-07-05 11:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('financialyear', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('source_qty', models.DecimalField(decimal_places=3, max_digits=16)),
                ('target_qty', models.DecimalField(decimal_places=3, max_digits=16)),
                ('is_cancelled', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_conversions', to='financialyear.financialyear')),
                ('source_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_out', to='catalogue.itemcompanymapping')),
                ('target_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions_in', to='catalogue.itemcompanymapping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('qty_in', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('qty_out', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('balance', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('voucher_type', models.CharField(max_length=20)),
                ('voucher_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('is_reversal', models.BooleanField(default=False)),
                ('is_opening', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger', to='financialyear.financialyear')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger', to='catalogue.itemcompanymapping')),
            ],
            options={
                'ordering': ['mapping_id', 'date', 'id'],
                'indexes': [models.Index(fields=['mapping', 'date'], name='stock_stock_mapping_e2db1b_idx'), models.Index(fields=['voucher_type', 'voucher_id'], name='stock_stock_voucher_ebf87d_idx')],
            },
        ),
    ]
