# Generated by Django 5.1.15 on 2026-07-05 11:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financialyear', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('voucher_type', models.CharField(max_length=20)),
                ('voucher_id', models.PositiveBigIntegerField()),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_ledger', to='financialyear.financialyear')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='parties.party')),
            ],
            options={
                'ordering': ['party_id', 'date', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['user', 'name'], name='parties_par_user_id_4687b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_party_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='partyledger',
            index=models.Index(fields=['party', 'date'], name='parties_par_party_i_342513_idx'),
        ),
        migrations.AddIndex(
            model_name='partyledger',
            index=models.Index(fields=['voucher_type', 'voucher_id'], name='parties_par_voucher_eb4d5d_idx'),
        ),
    ]
