# Generated by Django 5.1.15 on 2026-07-17 21:24

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cancelled', models.BooleanField(db_index=True, default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('voucher_type', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('SALE_DERIVED', 'Sale Derived')], max_length=20)),
                ('voucher_id', models.PositiveBigIntegerField()),
                ('charge_type', models.CharField(choices=[('DISCOUNT', 'Discount'), ('ROUND_OFF', 'Round Off'), ('CGST', 'CGST'), ('SGST', 'SGST')], max_length=20)),
                ('mode', models.CharField(choices=[('PERCENT', 'Percent'), ('AMOUNT', 'Amount')], default='PERCENT', max_length=20)),
                ('input_value', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_charges', to='ledgers.ledger')),
            ],
            options={
                'ordering': ['voucher_type', 'voucher_id', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['voucher_type', 'voucher_id'], name='vouchers_vo_voucher_b3fae7_idx')],
            },
        ),
    ]
