# Generated by Django 5.1.15 on 2026-07-20 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_settlementmode'),
        ('vouchers', '0002_vouchercharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.settlementmode'),
        ),
        migrations.AddField(
            model_name='received',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounts.settlementmode'),
        ),
    ]
