# Generated by Django 5.1.15 on 2026-07-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_payment_mode_received_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_ref',
            field=models.CharField(blank=True, help_text='UPI ref, UTR, cheque number, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='received',
            name='transaction_ref',
            field=models.CharField(blank=True, help_text='UPI ref, UTR, cheque number, etc.', max_length=100, null=True),
        ),
    ]
