# Generated by Django 5.1.15 on 2026-07-05 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_years', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='uniq_active_fy_per_user'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='fy_end_after_start')],
            },
        ),
    ]
