# Generated by Django 5.1.15 on 2026-07-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_settlementmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='max_companies',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
