# Generated by Django 5.1.15 on 2026-07-23 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_license_max_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlementmode',
            name='bank_type',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('TRANSFER', 'Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], help_text='Only relevant when category is bank.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='settlementmode',
            name='category',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank')], default='CASH', max_length=10),
        ),
        migrations.CreateModel(
            name='CompanyBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=40)),
                ('ifsc_code', models.CharField(blank=True, default='', max_length=20)),
                ('branch', models.CharField(blank=True, default='', max_length=120)),
                ('account_holder', models.CharField(blank=True, default='', max_length=200)),
                ('upi_id', models.CharField(blank=True, default='', max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'bank_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company',), name='unique_default_bank_per_company')],
            },
        ),
    ]
