# Generated by Django 5.1.15 on 2026-07-05 11:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('base_unit', models.CharField(default='pcs', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='accounts.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompanyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('opening_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('hsn_code', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gst_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings', to='catalogue.itemcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_mappings', to='accounts.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='catalogue.item')),
            ],
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user', 'name'], name='catalogue_i_user_id_e7479c_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_item_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='itemcategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_category_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='itemcompanymapping',
            index=models.Index(fields=['company', 'item'], name='catalogue_i_company_1e6d35_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemcompanymapping',
            constraint=models.UniqueConstraint(fields=('item', 'company'), name='uniq_item_per_company'),
        ),
    ]
