# Generated by Django 5.1.15 on 2026-07-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='base_unit',
            field=models.CharField(default='PCS', max_length=30),
        ),
    ]
